version: '3'
services:
  web:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - db
    ports:
    - "80:80"
    - "443:443"
    - "1812:1812/udp"
    - "1813:1813/udp"
   
    container_name: laravel
    networks:
    - lara_radius_network
    volumes:
    - ./laravel:/var/www/html
    - ./freeradius/3.0:/etc/freeradius/3.0
    # command: composer install --ignore-platform-reqs
  # freeradius:
  #   # image: freeradius/freeradius-server:latest
  #   build: 
  #     context: ./freeradius
  #     dockerfile: Dockerfile-free
  #   container_name: radius
  #   ports:
  #     - "1812:1812/udp"
  #     - "1813:1813/udp"
  #   networks:
  #     - lara_radius_network
  #   depends_on:
  #   - db
  #   volumes:
  #     - ./freeradius/mods-available/sql:/etc/freeradius/mods-available/sql
  #     - ./freeradius/sites-available/default:/etc/freeradius/sites-available/default
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    container_name: database
    restart: always
    networks:
    - lara_radius_network
    environment:
      MYSQL_ROOT_PASSWORD: new
      MYSQL_DATABASE: laravel
    volumes:
    - ./mysql:/var/lib/mysql
    - ./freeradius/mods-config/sql/main/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    - ./freeradius/mods-config/sql/main/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    # - ./mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    

  adminer:
    image: adminer:latest
    restart: always
    ports:
    - "8080:8080"
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
    networks:
    - lara_radius_network

networks:
  lara_radius_network:

