version: '3.6'
services:
  web:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    depends_on:
    - db
    ports:
    - "80:80"
    - "443:443"
   
    container_name: laravel
    networks:
    - laravel
    volumes:
    - ./laravel:/var/www/html
    # command: composer install --ignore-platform-reqs
  freeradius:
    # image: freeradius/freeradius-server:latest
    build: 
      context: ./freeradius
      dockerfile: Dockerfile
    container_name: radius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - laravel
    depends_on:
    - db
    volumes:
      - ./freeradius/mods-available/sql:/etc/freeradius/mods-available/sql
      - ./freeradius/sites-available/default:/etc/freeradius/sites-available/default
      # - ./freeradius/clients.conf:/etc/freeradius/clients.conf
    # command: ln -s /etc/freeradius/mods-available/sql /etc/freeradius/mods-enabled/sql
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    container_name: database
    networks:
    - laravel
    environment:
      MYSQL_ROOT_PASSWORD: new
      MYSQL_DATABASE: laravel
    volumes:
    - ./mysql:/var/lib/mysql
    - ./freeradius/mods-config/sql/main/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    - ./freeradius/mods-config/sql/main/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    # - ./mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  # adminer:
  #   image: adminer:latest
  #   ports:
  #   - "8080:8080"
  #   environment:
  #     ADMINER_PLUGINS: 'tables-filter tinymce'
  #   networks:
  #   - laravel
#  traefik:
#    image: traefik
#    ports:
#      - "8080:8080"
#      - "80:80"



networks:
  laravel:
    ipam:
      config:
      - subnet: 172.10.10.0/24

